add_rules("mode.debug", "mode.release")

add_repositories("my-repo repo")

-- SPIKE 2026-04-20: re-enabling edopro-core for the envpool integration
-- spike. The prior disable commit (bab5959) noted a "template with C
-- linkage" error from /usr/include/c++/11/bits/allocated_ptr.h.
add_requires(
    "ygopro-core 0.0.2", "edopro-core exodai-b118d05", "pybind11 2.13.*", "fmt 10.2.*", "glog 0.6.0",
    "sqlite3 3.43.0+200", "concurrentqueue 1.0.4", "unordered_dense 4.4.*",
    "sqlitecpp 3.2.1", "lua",
    -- ExodAI Phase P1 Primitive 1: state serialization runtime. Must stay in
    -- lockstep with the EDOPro client's vcpkg-supplied protobuf (both on the
    -- modern 4.x+/28.x lineage). See phase_p1_primitive_1_plan.md §1.4.
    "protobuf-cpp 28.x")


target("ygopro0_ygoenv")
    add_rules("python.library")
    add_files("ygoenv/ygoenv/ygopro0/*.cpp")
    add_packages("pybind11", "fmt", "glog", "concurrentqueue", "sqlitecpp", "unordered_dense", "ygopro-core")
    set_languages("c++17")
    if is_mode("release") then
        set_policy("build.optimization.lto", true)
        add_cxxflags("-march=native")
    end
    add_includedirs("ygoenv")

    after_build(function (target)
        local install_target = "$(projectdir)/ygoenv/ygoenv/ygopro0"
        os.cp(target:targetfile(), install_target)
        print("Copy target to " .. install_target)
    end)


target("ygopro_ygoenv")
    add_rules("python.library")
    add_files("ygoenv/ygoenv/ygopro/*.cpp")
    add_packages("pybind11", "fmt", "glog", "concurrentqueue", "sqlitecpp", "unordered_dense", "ygopro-core", "lua", "protobuf-cpp")
    set_languages("c++17")
    if is_mode("release") then
        set_policy("build.optimization.lto", true)
        add_cxxflags("-march=native")
        -- Keep debug symbols in release builds. Adds ~MB to .so size but
        -- no runtime cost, and makes gdb backtraces from core dumps
        -- useful when a segfault reaches the C++ engine. Without this,
        -- stack frames in gdb collapse to ?? at the ygopro-core boundary.
        set_symbols("debug")
    end
    add_includedirs("ygoenv")

    after_build(function (target)
        local install_target = "$(projectdir)/ygoenv/ygoenv/ygopro"
        os.cp(target:targetfile(), install_target)
        print("Copy target to " .. install_target)
    end)

target("edopro_ygoenv")
    add_rules("python.library")
    add_files("ygoenv/ygoenv/edopro/*.cpp")
    add_packages("pybind11", "fmt", "glog", "concurrentqueue", "sqlitecpp", "unordered_dense", "edopro-core", "protobuf-cpp")
    set_languages("c++17")
    if is_mode("release") then
        -- SPIKE 2026-04-20: LTO disabled on this target while closing the
        -- reset() crash. Hypothesis under test: whole-program LTO elides or
        -- misinlines the `try { } catch (...)` frame around LUAI_TRY in the
        -- Lua amalgam TU, so throws raised inside edo9300's
        -- check_lua_stack_unwinding self-test escape the supposed-protected
        -- region instead of being caught. See docs/edopro_envpool_spike.md §4.2.
        -- set_policy("build.optimization.lto", true)
        add_cxxflags("-march=native")
        -- SPIKE: keep debug symbols for named gdb backtraces (same policy as ygopro_ygoenv).
        set_symbols("debug")
    end
    add_includedirs("ygoenv")

    after_build(function (target)
        local install_target = "$(projectdir)/ygoenv/ygoenv/edopro"
        os.cp(target:targetfile(), install_target)
        print("Copy target to " .. install_target)
    end)


-- ---------------------------------------------------------------------------
-- ExodAI Phase P1 Primitive 1 (chunk 2): serialization unit tests.
--
-- The ocgcore submodule lives outside this repo at
-- /mnt/c/Users/Joe/Documents/edopro/edopro/ocgcore/. We build the chunk-2
-- tests as standalone binaries here (not inside the submodule) because
-- xmake's project search and protobuf integration only work cleanly
-- against this xmake.lua's package context. See chunk-1 plan §10's
-- cross-repo notes — the eventual fork-tagged solution moves these to
-- ocgcore/serialize/tests/ with their own xmake.lua.
--
-- Run:
--     xmake build serialize_test_schema serialize_test_handles
--     xmake run serialize_test_schema
--     xmake run serialize_test_handles
-- ---------------------------------------------------------------------------

local ocgcore_serialize = "/mnt/c/Users/Joe/Documents/edopro/edopro/ocgcore/serialize"

target("serialize_test_schema")
    set_kind("binary")
    set_languages("c++17")
    set_default(false)  -- not built by default `xmake build`
    -- The .pb.cc/.pb.h are pre-generated by `make proto` in the serialize
    -- directory before this target builds. xmake's protobuf.cpp rule
    -- doesn't tolerate the relative-vs-absolute path mismatch when the
    -- .proto lives outside the project tree, so we sidestep the rule
    -- entirely. Pre-generation is invoked from a shell wrapper or by the
    -- developer running `cd $ocgcore_serialize && make proto` once.
    --
    -- Protoc convergence: this target's on_load -> `make proto` uses the
    -- same xmake-managed `protobuf-cpp 28.x` package as the production
    -- ygoenv build path (both via xrepo env / add_requires), so both
    -- protoc invocations resolve to the identical xmake-installed
    -- binary. No version-drift risk between test gencode and production
    -- runtime as long as both pins stay aligned. (EDOPro/MSBuild uses
    -- vcpkg's protoc — separate gencode tree, not shared with ygoenv,
    -- so version drift between vcpkg and xmake is by design per
    -- phase_p1_primitive_1_plan.md §1.3.)
    on_load(function (target)
        -- Idempotent pre-gen at target load. Hooks into xmake's build
        -- phase before add_files glob expansion.
        os.execv("make", {"-C", "/mnt/c/Users/Joe/Documents/edopro/edopro/ocgcore/serialize", "proto"})
    end)
    add_files(ocgcore_serialize .. "/tests/test_schema.cpp")
    add_files(ocgcore_serialize .. "/ocg_state.pb.cc")
    add_includedirs(ocgcore_serialize)
    add_packages("protobuf-cpp")

target("serialize_test_handles")
    set_kind("binary")
    set_languages("c++17")
    set_default(false)
    add_files(ocgcore_serialize .. "/tests/test_handles.cpp")
    add_includedirs(ocgcore_serialize)
    -- No protobuf dep — handle_table.h is pure header-only template.

target("serialize_test_save")
    set_kind("binary")
    set_languages("c++17")
    set_default(false)
    -- Pre-gen .pb.cc same way serialize_test_schema does.
    on_load(function (target)
        os.execv("make", {"-C", "/mnt/c/Users/Joe/Documents/edopro/edopro/ocgcore/serialize", "proto"})
    end)
    add_files(ocgcore_serialize .. "/tests/test_save.cpp")
    add_files(ocgcore_serialize .. "/ocg_state.pb.cc")
    add_includedirs(ocgcore_serialize, ocgcore_serialize .. "/..")
    -- Links the edopro-core static lib for OCG_CreateDuel /
    -- OCG_DuelSaveState (defined in ocgapi.cpp + serialize/save_state.cpp,
    -- both compiled into the package's static lib via the chunk-1+
    -- overlay).
    add_packages("edopro-core", "protobuf-cpp")

target("alphazero_mcts")
    add_rules("python.library")
    add_files("mcts/mcts/alphazero/*.cpp")
    add_packages("pybind11")
    set_languages("c++17")
    if is_mode("release") then
        set_policy("build.optimization.lto", true)
        add_cxxflags("-march=native")
    end
    add_includedirs("mcts")

    after_build(function (target)
        local install_target = "$(projectdir)/mcts/mcts/alphazero"
        os.cp(target:targetfile(), install_target)
        print("Copy target to " .. install_target)
        os.run("pybind11-stubgen mcts.alphazero.alphazero_mcts -o %s", "$(projectdir)/mcts")
    end)
